(()=>{'use strict';
const SUPABASE_URL='https://feoyjasuvrqxzhskqzye.supabase.co';const SUPABASE_KEY='sb_publishable_ehho8PNFtVSRiBn7GaBl9Q_Tl1mYVT0';const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);const drawer=$('drawer'),profileDrawer=$('profileDrawer');const openDrawer=()=>drawer?.classList.add('open'),closeDrawer=()=>drawer?.classList.remove('open');const openProfile=()=>{profileDrawer?.classList.add('open');profileDrawer?.setAttribute('aria-hidden','false')},closeProfile=()=>{profileDrawer?.classList.remove('open');profileDrawer?.setAttribute('aria-hidden','true')};
$('mobileTools')?.addEventListener('click',openDrawer);$('drawerClose')?.addEventListener('click',closeDrawer);drawer?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeDrawer));$('profileOpen')?.addEventListener('click',openProfile);$('profileClose')?.addEventListener('click',closeProfile);$('drawerProfile')?.addEventListener('click',()=>{closeDrawer();openProfile()});
const signOut=async()=>{await client.auth.signOut();window.location.replace('../auth.html')};$('profileLogout')?.addEventListener('click',signOut);$('drawerLogout')?.addEventListener('click',signOut);$('drawerLogoutMobile')?.addEventListener('click',signOut);
function updateActive(){const id=location.hash.replace('#','')||'overview';document.querySelectorAll('.side-link').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id))}window.addEventListener('hashchange',updateActive);updateActive();
function updateClock(){const d=new Date();if($('clock'))$('clock').textContent=d.toLocaleTimeString([], {hour12:false})}updateClock();setInterval(updateClock,1000);
function setAvatar(el,url,name){if(!el)return;el.innerHTML='';if(url){const img=document.createElement('img');img.src=url;img.alt='Profile photo';el.appendChild(img)}else el.textContent=(name||'M').trim().charAt(0).toUpperCase()||'M'}function message(text,ok=true){const e=$('profileMessage');if(e){e.textContent=text;e.style.color=ok?'#00E676':'#FF7B70'}}
const labels={GOLD:['Gold','الذهب','GC!'],NASDAQ:['Nasdaq','ناسداك','NQ!'],SP500:['S&P 500','S&P 500','ES!'],DOLLAR:['Dollar Index','مؤشر الدولار','DX!']};const cfdSymbols={GOLD:'XAUUSD',NASDAQ:'NAS100',SP500:'US500',DOLLAR:'DXY'};let selectedSymbol='GOLD',selectedMarket='FUTURES';
const assetLogos={GOLD:'https://img.favpng.com/23/1/3/gold-bar-png-favpng-7h7MYZMeJCyT7NjvigdZedDA9.jpg',NASDAQ:'https://i.imgur.com/b8ZZHNS.png',SP500:'https://i.imgur.com/pfGJXOL.png',DOLLAR:'https://i.imgur.com/ZzhJihh.png'};
const quoteSymbols={GOLD:'GC=F',NASDAQ:'NQ=F',SP500:'ES=F',DOLLAR:'DX-Y.NYB'};const quotePrecision={GOLD:2,NASDAQ:2,SP500:2,DOLLAR:3};let liveQuotes={};
function money(value,key){if(!Number.isFinite(Number(value)))return '—';const p=quotePrecision[key]??2;return Number(value).toLocaleString('en-US',{minimumFractionDigits:p,maximumFractionDigits:p})}
function compactVolume(value){if(!Number.isFinite(Number(value)))return '—';const n=Number(value);if(n>=1e9)return `${(n/1e9).toFixed(2)}B`;if(n>=1e6)return `${(n/1e6).toFixed(2)}M`;if(n>=1e3)return `${(n/1e3).toFixed(1)}K`;return n.toLocaleString('en-US')}
function marketStateLabel(state){return state==='REGULAR'||state==='OPEN'?'LIVE':state==='PRE'||state==='PREPRE'?'PRE-MARKET':state==='POST'||state==='POSTPOST'?'AFTER-HOURS':'MARKET CLOSED'}
function marketIsOpen(state){return state==='REGULAR'||state==='OPEN'}
function paintMarketState(state){const live=marketIsOpen(state);document.querySelectorAll('.banner-state').forEach(el=>{el.classList.toggle('live',live);el.classList.toggle('closed',!live);el.innerHTML=`<i></i><span>${live?'LIVE':'MARKET CLOSED'}</span>`;el.style.lineHeight='1.1';el.style.textAlign='center';el.style.fontSize=live?'9px':'8px';el.style.letterSpacing=live?'.04em':'.03em'});const top=document.querySelector('.live-status');if(top){const dot=top.querySelector('i');const text=top.querySelector('span');if(dot)dot.style.background=live?'#00e676':'#ffb020';if(dot)dot.style.boxShadow=live?'0 0 10px #00e676':'0 0 10px #ffb020';if(text){text.textContent=live?'LIVE MARKETS':'MARKET CLOSED';text.style.color=live?'':'#9a8a67';text.style.fontSize=live?'9px':'8px';text.style.letterSpacing='.04em'}}}
function paintBannerStats(q,key){const stats=document.querySelectorAll('.asset-banner .banner-stat');if(stats.length<3||!q)return;stats[0].querySelector('strong').textContent=money(q.dayHigh,key);stats[1].querySelector('strong').textContent=money(q.dayLow,key);stats[2].querySelector('strong').textContent=compactVolume(q.volume)}
function applyLiveQuote(key,q){if(!q)return;liveQuotes[key]=q;const price=money(q.price,key),change=Number(q.change),pct=Number(q.changePct);document.querySelectorAll(`.asset[data-symbol="${key}"] [data-live-price]`).forEach(el=>el.textContent=price);if(key===selectedSymbol){if($('assetPrice'))$('assetPrice').textContent=price;if($('assetChange'))$('assetChange').textContent=Number.isFinite(pct)?`${change>=0?'+':''}${money(change,key)} (${pct>=0?'+':''}${pct.toFixed(2)}%)`:'—';const line=$('.price-line span');if(line)line.textContent=price;paintBannerStats(q,key);paintMarketState(q.marketState)}}
async function refreshMarketData(){try{const r=await fetch('/api/market-quotes',{cache:'no-store'});if(!r.ok)throw new Error('Market data unavailable');const json=await r.json();(json.data||[]).forEach(q=>{const key=Object.keys(quoteSymbols).find(k=>quoteSymbols[k]===q.symbol);if(key)applyLiveQuote(key,q)});const status=$('marketDataStatus');if(status)status.textContent='LIVE DATA'}catch(e){const status=$('marketDataStatus');if(status)status.textContent='DATA UNAVAILABLE'}}
function paintAssetLogos(){document.querySelectorAll('.asset').forEach(btn=>{const visual=btn.querySelector('.asset-visual');if(!visual)return;visual.className='asset-visual';visual.innerHTML=`<img src="${assetLogos[btn.dataset.symbol]||assetLogos.GOLD}" alt="${btn.dataset.symbol} logo" loading="eager">`;const copy=btn.querySelector('.asset-copy');if(copy){const name=copy.querySelector('b'),code=copy.querySelector('small');if(name){name.style.fontSize='12px';name.style.fontWeight='800';name.style.color='#F1F6FC';name.style.letterSpacing='-.01em'}if(code){code.style.fontSize='9px';code.style.fontWeight='700';code.style.color='#8FA1B8';code.style.letterSpacing='.02em'}}})}
function updateBannerArt(symbol){const art=document.querySelector('.banner-art');if(!art)return;art.className='banner-art';art.innerHTML=`<img src="${assetLogos[symbol]||assetLogos.GOLD}" alt="${symbol} logo" loading="eager">`}
function updateAsset(btn){paintAssetLogos();document.querySelectorAll('.asset').forEach(b=>b.classList.remove('active'));btn.classList.add('active');selectedSymbol=btn.dataset.symbol;const info=labels[selectedSymbol]||labels.GOLD;const ar=document.documentElement.lang==='ar';const name=ar?info[1]:info[0];const symbol=selectedMarket==='CFD'?cfdSymbols[selectedSymbol]:info[2];if($('instrumentTitle')){$('instrumentTitle').textContent=name.toUpperCase();$('instrumentTitle').style.fontSize=selectedMarket==='FUTURES'?'27px':'20px';$('instrumentTitle').style.letterSpacing=selectedMarket==='FUTURES'?'.02em':'0'}if($('instrumentSymbol')){$('instrumentSymbol').textContent=symbol;$('instrumentSymbol').style.fontSize=selectedMarket==='FUTURES'?'13px':'10px';$('instrumentSymbol').style.fontWeight=selectedMarket==='FUTURES'?'800':'600'}if($('chartTitle'))$('chartTitle').textContent=`${name} · ${symbol}`;if($('assetMarketLabel'))$('assetMarketLabel').textContent=selectedMarket;document.querySelectorAll('.asset').forEach(asset=>{const assetSymbol=asset.dataset.symbol,assetInfo=labels[assetSymbol]||labels.GOLD,assetName=ar?assetInfo[1]:assetInfo[0],assetCode=selectedMarket==='CFD'?cfdSymbols[assetSymbol]:assetInfo[2],small=asset.querySelector('.asset-copy small');if(small)small.textContent=`${assetName.toUpperCase()} · ${assetCode}`});const q=liveQuotes[selectedSymbol];if(q)applyLiveQuote(selectedSymbol,q);else {if($('assetPrice'))$('assetPrice').textContent='—';if($('assetChange'))$('assetChange').textContent='Loading live quote…';const p=$('.price-line span');if(p)p.textContent='—'}updateBannerArt(selectedSymbol);renderCandles()}
document.querySelectorAll('.asset').forEach(b=>b.addEventListener('click',()=>updateAsset(b)));document.querySelectorAll('.market-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.market-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedMarket=b.dataset.market;const active=document.querySelector('.asset.active')||document.querySelector('.asset');if(active)updateAsset(active)}));
function applyLanguage(lang){const ar=lang==='ar';document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';document.querySelectorAll('[data-en][data-ar]').forEach(el=>el.textContent=ar?el.dataset.ar:el.dataset.en);const input=$('marketSearch');if(input)input.placeholder=ar?input.dataset.placeholderAr:input.dataset.placeholderEn;if($('languageToggle'))$('languageToggle').textContent=ar?'English':'عربي';localStorage.setItem('econova-client-language',lang);const active=document.querySelector('.asset.active');if(active)updateAsset(active)}
let lightThemeLink=null;function applyTheme(theme){document.body.classList.toggle('light',theme==='light');if(!lightThemeLink){lightThemeLink=document.createElement('link');lightThemeLink.rel='stylesheet';lightThemeLink.href='light-theme.css?v=20260908-1';document.head.appendChild(lightThemeLink)}lightThemeLink.disabled=theme!=='light';if($('themeToggle'))$('themeToggle').textContent=theme==='light'?'☾':'☼';localStorage.setItem('econova-client-theme',theme)}$('languageToggle')?.addEventListener('click',()=>applyLanguage(document.documentElement.lang==='ar'?'en':'ar'));$('themeToggle')?.addEventListener('click',()=>applyTheme(document.body.classList.contains('light')?'dark':'light'));applyTheme(localStorage.getItem('econova-client-theme')||'dark');applyLanguage(localStorage.getItem('econova-client-language')||'en');
function renderCandles(){const box=$('candles');if(!box)return;box.innerHTML='';const heights=[42,57,38,66,50,73,61,45,78,54,69,49,82,64,72,88,62,77,69,91,74,83,70,96];heights.forEach((h,i)=>{const c=document.createElement('i');c.className='candle'+(i%5===0||i%7===0?' down':'');c.style.height=`${Math.max(18,h/2)}%`;c.style.transform=`translateY(${(i%4-1)*8}px)`;box.appendChild(c)})}paintAssetLogos();renderCandles();updateBannerArt(selectedSymbol);
const search=$('marketSearch');search?.addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.toLowerCase();const match=[...document.querySelectorAll('.asset')].find(a=>a.innerText.toLowerCase().includes(q));if(match){updateAsset(match);document.querySelector('#markets')?.scrollIntoView({behavior:'smooth',block:'center'})}}});window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search?.focus()}});
async function loadProfile(session){const user=session.user;const{data,error}=await client.from('profiles').select('full_name,phone,email,avatar_url').eq('id',user.id).maybeSingle();if(error)throw error;const profile=data||{},email=user.email||profile.email||'',name=profile.full_name||user.user_metadata?.full_name||email.split('@')[0]||'Member';['topName','welcomeName','profileNamePreview'].forEach(id=>{if($(id))$(id).textContent=name});if($('profileEmailPreview'))$('profileEmailPreview').textContent=email;if($('fullName'))$('fullName').value=profile.full_name||'';if($('phone'))$('phone').value=profile.phone||'';if($('emailProfile'))$('emailProfile').value=email;setAvatar($('topAvatar'),profile.avatar_url,name);setAvatar($('profileAvatar'),profile.avatar_url,name);return{user,profile,email,name}}
let current=null;$('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!current)return;const btn=$('saveProfile');btn.disabled=true;message('Saving…');try{const payload={id:current.user.id,full_name:$('fullName').value.trim()||null,phone:$('phone').value.trim()||null,email:current.email,avatar_url:current.profile.avatar_url||null};const{error}=await client.from('profiles').upsert(payload,{onConflict:'id'});if(error)throw error;current.profile={...current.profile,...payload};await loadProfile({user:current.user});message('Profile saved successfully.')}catch(err){message(err?.message||'Could not save your profile.',false)}finally{btn.disabled=false}});
$('avatarInput')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file||!current)return;if(file.size>5*1024*1024){message('Photo must be 5 MB or smaller.',false);e.target.value='';return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){message('Use JPG, PNG or WebP.',false);e.target.value='';return}message('Uploading photo…');try{const ext=file.name.split('.').pop()?.toLowerCase()||'jpg',path=`${current.user.id}/avatar.${ext}`;const{error}=await client.storage.from('profile-avatars').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(error)throw error;const{data}=client.storage.from('profile-avatars').getPublicUrl(path);const{error:dbError}=await client.from('profiles').upsert({id:current.user.id,full_name:$('fullName').value.trim()||current.profile.full_name||null,phone:$('phone').value.trim()||current.profile.phone||null,email:current.email,avatar_url:data.publicUrl},{onConflict:'id'});if(dbError)throw dbError;current.profile.avatar_url=data.publicUrl;setAvatar($('topAvatar'),data.publicUrl,current.name);setAvatar($('profileAvatar'),data.publicUrl,current.name);message('Profile photo updated.')}catch(err){message(err?.message||'Could not upload the photo.',false)}finally{e.target.value=''}});
client.auth.getSession().then(async({data,error})=>{if(error||!data?.session){window.location.replace('../auth.html');return}try{current=await loadProfile(data.session)}catch(err){message(err?.message||'Profile could not be loaded.',false)}refreshMarketData();setInterval(refreshMarketData,10000)});client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session)window.location.replace('../auth.html')});
})();