(()=>{'use strict';
const SUPABASE_URL='https://feoyjasuvrqxzhskqzye.supabase.co';const SUPABASE_KEY='sb_publishable_ehho8PNFtVSRiBn7GaBl9Q_Tl1mYVT0';const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});const $=id=>document.getElementById(id);
const drawer=$('drawer'),profileDrawer=$('profileDrawer');const openDrawer=()=>drawer?.classList.add('open'),closeDrawer=()=>drawer?.classList.remove('open');const openProfile=()=>{profileDrawer?.classList.add('open');profileDrawer?.setAttribute('aria-hidden','false')},closeProfile=()=>{profileDrawer?.classList.remove('open');profileDrawer?.setAttribute('aria-hidden','true')};
$('mobileTools')?.addEventListener('click',openDrawer);$('drawerClose')?.addEventListener('click',closeDrawer);drawer?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeDrawer));$('profileOpen')?.addEventListener('click',openProfile);$('profileClose')?.addEventListener('click',closeProfile);$('drawerProfile')?.addEventListener('click',()=>{closeDrawer();openProfile()});
const signOut=async()=>{await client.auth.signOut();window.location.replace('../auth.html')};$('profileLogout')?.addEventListener('click',signOut);$('drawerLogout')?.addEventListener('click',signOut);$('drawerLogoutMobile')?.addEventListener('click',signOut);
function updateActive(){const id=location.hash.replace('#','')||'overview';document.querySelectorAll('.side-link').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id))}window.addEventListener('hashchange',updateActive);updateActive();
function updateClock(){const d=new Date();if($('clock'))$('clock').textContent=d.toLocaleTimeString([], {hour12:false});}updateClock();setInterval(updateClock,1000);
function setAvatar(el,url,name){if(!el)return;el.innerHTML='';if(url){const img=document.createElement('img');img.src=url;img.alt='Profile photo';el.appendChild(img)}else el.textContent=(name||'M').trim().charAt(0).toUpperCase()||'M'}function message(text,ok=true){const e=$('profileMessage');if(e){e.textContent=text;e.style.color=ok?'#00E676':'#FF7B70'}}
const labels={GOLD:['Gold','الذهب','GC!'],NASDAQ:['Nasdaq','ناسداك','NQ!'],SP500:['S&P 500','S&P 500','ES!'],DOLLAR:['Dollar Index','مؤشر الدولار','DX!']};const cfdSymbols={GOLD:'XAUUSD',NASDAQ:'NAS100',SP500:'US500',DOLLAR:'DXY'};let selectedSymbol='GOLD',selectedMarket='FUTURES';
const assetLogos={GOLD:'https://img.favpng.com/23/1/3/gold-bar-png-favpng-7h7MYZMeJCyT7NjvigdZedDA9.jpg',NASDAQ:'https://i.imgur.com/b8ZZHNS.png',SP500:'https://i.imgur.com/pfGJXOL.png',DOLLAR:'https://i.imgur.com/ZzhJihh.png'};
function paintAssetLogos(){document.querySelectorAll('.asset').forEach(btn=>{const visual=btn.querySelector('.asset-visual');if(!visual)return;visual.className='asset-visual';visual.innerHTML=`<img src="${assetLogos[btn.dataset.symbol]||assetLogos.GOLD}" alt="${btn.dataset.symbol} logo" loading="eager">`})}
function updateBannerArt(symbol){const art=document.querySelector('.banner-art');if(!art)return;art.className='banner-art';art.innerHTML=`<img src="${assetLogos[symbol]||assetLogos.GOLD}" alt="${symbol} logo" loading="eager">`}
function updateAsset(btn){paintAssetLogos();document.querySelectorAll('.asset').forEach(b=>b.classList.remove('active'));btn.classList.add('active');selectedSymbol=btn.dataset.symbol;const info=labels[selectedSymbol]||labels.GOLD;const ar=document.documentElement.lang==='ar';const name=ar?info[1]:info[0];const symbol=selectedMarket==='CFD'?cfdSymbols[selectedSymbol]:info[2];if($('instrumentTitle')){$('instrumentTitle').textContent=name.toUpperCase();$('instrumentTitle').style.fontSize=selectedMarket==='FUTURES'?'27px':'20px';$('instrumentTitle').style.letterSpacing=selectedMarket==='FUTURES'?'.02em':'0'}if($('instrumentSymbol')){$('instrumentSymbol').textContent=symbol;$('instrumentSymbol').style.fontSize=selectedMarket==='FUTURES'?'13px':'10px';$('instrumentSymbol').style.fontWeight=selectedMarket==='FUTURES'?'800':'600'}if($('chartTitle'))$('chartTitle').textContent=`${name} · ${symbol}`;if($('assetMarketLabel'))$('assetMarketLabel').textContent=selectedMarket;document.querySelectorAll('.asset').forEach(asset=>{const assetSymbol=asset.dataset.symbol;const assetInfo=labels[assetSymbol]||labels.GOLD;const assetName=ar?assetInfo[1]:assetInfo[0];const assetCode=selectedMarket==='CFD'?cfdSymbols[assetSymbol]:assetInfo[2];const small=asset.querySelector('.asset-copy small');if(small)small.textContent=`${assetName.toUpperCase()} · ${assetCode}`});if($('assetPrice'))$('assetPrice').textContent=selectedSymbol==='GOLD'?'3,642.50':'—';if($('assetChange'))$('assetChange').textContent=selectedSymbol==='GOLD'?'+12.30 (+0.34%)':'Live quote pending';const p=$('.price-line span');if(p)p.textContent=selectedSymbol==='GOLD'?'3,642.50':'—';updateBannerArt(selectedSymbol);renderCandles()}
document.querySelectorAll('.asset').forEach(b=>b.addEventListener('click',()=>updateAsset(b)));
document.querySelectorAll('.market-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.market-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedMarket=b.dataset.market;const active=document.querySelector('.asset.active')||document.querySelector('.asset');if(active)updateAsset(active)}));
function applyLanguage(lang){const ar=lang==='ar';document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';document.querySelectorAll('[data-en][data-ar]').forEach(el=>el.textContent=ar?el.dataset.ar:el.dataset.en);const input=$('marketSearch');if(input)input.placeholder=ar?input.dataset.placeholderAr:input.dataset.placeholderEn;if($('languageToggle'))$('languageToggle').textContent=ar?'English':'عربي';localStorage.setItem('econova-client-language',lang);const active=document.querySelector('.asset.active');if(active)updateAsset(active)}
function applyTheme(theme){document.body.classList.toggle('light',theme==='light');if($('themeToggle'))$('themeToggle').textContent=theme==='light'?'☾':'☼';localStorage.setItem('econova-client-theme',theme)}$('languageToggle')?.addEventListener('click',()=>applyLanguage(document.documentElement.lang==='ar'?'en':'ar'));$('themeToggle')?.addEventListener('click',()=>applyTheme(document.body.classList.contains('light')?'dark':'light'));applyTheme(localStorage.getItem('econova-client-theme')||'dark');applyLanguage(localStorage.getItem('econova-client-language')||'en');
function renderCandles(){const box=$('candles');if(!box)return;box.innerHTML='';const heights=[42,57,38,66,50,73,61,45,78,54,69,49,82,64,72,88,62,77,69,91,74,83,70,96];heights.forEach((h,i)=>{const c=document.createElement('i');c.className='candle'+(i%5===0||i%7===0?' down':'');c.style.height=`${Math.max(18,h/2)}%`;c.style.transform=`translateY(${(i%4-1)*8}px)`;box.appendChild(c)})}paintAssetLogos();renderCandles();updateBannerArt(selectedSymbol);
const search=$('marketSearch');search?.addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.toLowerCase();const match=[...document.querySelectorAll('.asset')].find(a=>a.innerText.toLowerCase().includes(q));if(match){updateAsset(match);document.querySelector('#markets')?.scrollIntoView({behavior:'smooth',block:'center'})}}});window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search?.focus()}});
async function loadProfile(session){const user=session.user;const{data,error}=await client.from('profiles').select('full_name,phone,email,avatar_url').eq('id',user.id).maybeSingle();if(error)throw error;const profile=data||{};const email=user.email||profile.email||'';const name=profile.full_name||user.user_metadata?.full_name||email.split('@')[0]||'Member';['topName','welcomeName','profileNamePreview'].forEach(id=>{if($(id))$(id).textContent=name});if($('profileEmailPreview'))$('profileEmailPreview').textContent=email;if($('fullName'))$('fullName').value=profile.full_name||'';if($('phone'))$('phone').value=profile.phone||'';if($('emailProfile'))$('emailProfile').value=email;setAvatar($('topAvatar'),profile.avatar_url,name);setAvatar($('profileAvatar'),profile.avatar_url,name);return{user,profile,email,name}}
let current=null;$('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!current)return;const btn=$('saveProfile');btn.disabled=true;message('Saving…');try{const payload={id:current.user.id,full_name:$('fullName').value.trim()||null,phone:$('phone').value.trim()||null,email:current.email,avatar_url:current.profile.avatar_url||null};const{error}=await client.from('profiles').upsert(payload,{onConflict:'id'});if(error)throw error;current.profile={...current.profile,...payload};await loadProfile({user:current.user});message('Profile saved successfully.')}catch(err){message(err?.message||'Could not save your profile.',false)}finally{btn.disabled=false}});
$('avatarInput')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file||!current)return;if(file.size>5*1024*1024){message('Photo must be 5 MB or smaller.',false);e.target.value='';return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){message('Use JPG, PNG or WebP.',false);e.target.value='';return}message('Uploading photo…');try{const ext=file.name.split('.').pop()?.toLowerCase()||'jpg',path=`${current.user.id}/avatar.${ext}`;const{error}=await client.storage.from('profile-avatars').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(error)throw error;const{data}=client.storage.from('profile-avatars').getPublicUrl(path);const{error:dbError}=await client.from('profiles').upsert({id:current.user.id,full_name:$('fullName').value.trim()||current.profile.full_name||null,phone:$('phone').value.trim()||current.profile.phone||null,email:current.email,avatar_url:data.publicUrl},{onConflict:'id'});if(dbError)throw dbError;current.profile.avatar_url=data.publicUrl;setAvatar($('topAvatar'),data.publicUrl,current.name);setAvatar($('profileAvatar'),data.publicUrl,current.name);message('Profile photo updated.')}catch(err){message(err?.message||'Could not upload the photo.',false)}finally{e.target.value=''}});
client.auth.getSession().then(async({data,error})=>{if(error||!data?.session){window.location.replace('../auth.html');return}try{current=await loadProfile(data.session)}catch(err){message(err?.message||'Profile could not be loaded.',false)}});client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session)window.location.replace('../auth.html')});
})();