(()=>{'use strict';
const $=id=>document.getElementById(id);const qsa=s=>[...document.querySelectorAll(s)];
const drawer=$('drawer'),profile=$('profileDrawer'),notifications=$('notificationDrawer'),backdrop=$('drawerBackdrop'),palette=$('commandPalette');
function closePanels(){[drawer,profile,notifications].forEach(x=>x?.classList.remove('open'));[drawer,profile,notifications].forEach(x=>x?.setAttribute('aria-hidden','true'));backdrop?.classList.remove('open')}
function openPanel(panel){closePanels();panel?.classList.add('open');panel?.setAttribute('aria-hidden','false');if(panel!==drawer)backdrop?.classList.add('open')}
$('mobileTools')?.addEventListener('click',()=>openPanel(drawer));$('drawerClose')?.addEventListener('click',closePanels);$('drawerBackdrop')?.addEventListener('click',closePanels);$('profileOpen')?.addEventListener('click',()=>openPanel(profile));$('profileClose')?.addEventListener('click',closePanels);$('sideProfile')?.addEventListener('click',()=>openPanel(profile));$('drawerProfile')?.addEventListener('click',()=>openPanel(profile));$('notificationsOpen')?.addEventListener('click',()=>openPanel(notifications));$('notificationsClose')?.addEventListener('click',closePanels);qsa('.drawer a').forEach(a=>a.addEventListener('click',()=>setTimeout(closePanels,80)));
function openPalette(){palette?.classList.add('open');palette?.setAttribute('aria-hidden','false');$('commandInput')?.focus();renderCommands('')};function closePalette(){palette?.classList.remove('open');palette?.setAttribute('aria-hidden','true')};function renderCommands(query){const q=(query||'').trim().toLowerCase();qsa('#commandItems button').forEach(b=>b.hidden=q&&!b.textContent.toLowerCase().includes(q))}
$('commandInput')?.addEventListener('input',e=>renderCommands(e.target.value));qsa('#commandItems button').forEach(b=>b.addEventListener('click',()=>{closePalette();document.querySelector(b.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'})}));window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape'){closePalette();closePanels()}});palette?.addEventListener('click',e=>{if(e.target===palette)closePalette()});
const toast=text=>{const t=$('toast');if(!t)return;t.querySelector('span').textContent=text;t.classList.add('show');clearTimeout(window.__econovaToast);window.__econovaToast=setTimeout(()=>t.classList.remove('show'),2400)};
$('refreshData')?.addEventListener('click',()=>{toast(document.documentElement.lang==='ar'?'جارٍ تحديث بيانات السوق…':'Refreshing market data…');window.dispatchEvent(new Event('econova:refresh'))});$('focusRisk')?.addEventListener('click',()=>document.querySelector('#calendar')?.scrollIntoView({behavior:'smooth'}));qsa('[data-action]').forEach(b=>b.addEventListener('click',()=>{const ar=document.documentElement.lang==='ar';toast(b.dataset.action==='journal'?(ar?'السجل جاهز للمراجعة':'Journal is ready to review'):ar?'راجع قواعد الاستراتيجية قبل التنفيذ':'Review your strategy rules before execution')}));
function activeNav(){const links=qsa('.side-link');const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);const y=window.scrollY+130;let current=sections[0]?.id;sections.forEach(s=>{if(s.offsetTop<=y)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))}window.addEventListener('scroll',activeNav,{passive:true});activeNav();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}window.addEventListener('online',()=>{const s=$('marketDataStatus');if(s)s.textContent='ONLINE · MARKET FEED AVAILABLE'});window.addEventListener('offline',()=>{const s=$('marketDataStatus');if(s)s.textContent='OFFLINE · LAST KNOWN STATE'});
})();