(()=>{'use strict';
const $=id=>document.getElementById(id), qsa=s=>[...document.querySelectorAll(s)];
const PAGES={overview:'index.html',markets:'markets.html',intelligence:'intelligence.html',performance:'performance.html',calendar:'risk-calendar.html',education:'education.html',notifications:'notifications.html',profile:'profile.html'};
const I18N={en:{dir:'ltr',brand:'ECONOVA',menu:'Menu',notifications:'Notifications',language:'العربية',theme:'Theme',light:'Light',dark:'Dark',overview:'Overview',markets:'Markets',intelligence:'Intelligence',performance:'Performance',calendar:'Risk Calendar',education:'Education',profile:'Profile',refresh:'Refresh',close:'Close',save:'Save changes',saved:'Changes saved',logout:'Log out',online:'ONLINE · MARKET FEED AVAILABLE',offline:'OFFLINE · LAST KNOWN STATE',updated:'Market data updated',refreshing:'Refreshing market data…',menuTitle:'Workspace',timeframe:'Timeframe',market:'Market',settings:'Settings',journal:'Journal',strategy:'Strategy rules',risk:'Risk calendar',noAction:'Action unavailable'},ar:{dir:'rtl',brand:'ECONOVA',menu:'القائمة',notifications:'الإشعارات',language:'English',theme:'المظهر',light:'نهاري',dark:'ليلي',overview:'نظرة عامة',markets:'الأسواق',intelligence:'التحليل',performance:'الأداء',calendar:'تقويم المخاطر',education:'التعليم',profile:'الملف الشخصي',refresh:'تحديث',close:'إغلاق',save:'حفظ التغييرات',saved:'تم حفظ التغييرات',logout:'تسجيل الخروج',online:'متصل · بيانات السوق متاحة',offline:'غير متصل · آخر حالة معروفة',updated:'تم تحديث بيانات السوق',refreshing:'جارٍ تحديث بيانات السوق…',menuTitle:'مساحة العمل',timeframe:'الإطار الزمني',market:'السوق',settings:'الإعدادات',journal:'السجل',strategy:'قواعد الاستراتيجية',risk:'تقويم المخاطر',noAction:'الإجراء غير متاح'}};
function lang(){return localStorage.getItem('econova-language')||document.documentElement.lang||'en'}
function tr(k){return (I18N[lang()]||I18N.en)[k]||k}
function applyLanguage(){const l=lang(),t=I18N[l]||I18N.en;document.documentElement.lang=l;document.documentElement.dir=t.dir;qsa('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(t[k])el.textContent=t[k]});qsa('[data-i18n-title]').forEach(el=>{const k=el.dataset.i18nTitle;if(t[k])el.title=t[k]});qsa('[data-i18n-aria]').forEach(el=>{const k=el.dataset.i18nAria;if(t[k])el.setAttribute('aria-label',t[k])});qsa('[data-placeholder-i18n]').forEach(el=>{const k=el.dataset.placeholderI18n;if(t[k])el.placeholder=t[k]});document.querySelectorAll('[data-lang-label]').forEach(el=>el.textContent=t.language);document.querySelectorAll('[data-theme-label]').forEach(el=>el.textContent=t.theme)}
function theme(){return localStorage.getItem('econova-theme')||'dark'}
function applyTheme(){const v=theme();document.documentElement.dataset.theme=v;document.body?.setAttribute('data-theme',v);qsa('[data-theme-icon]').forEach(el=>el.textContent=v==='dark'?'☀':'☾');qsa('[data-theme-label]').forEach(el=>el.textContent=v==='dark'?tr('light'):tr('dark'))}
function go(page,hash=''){const url=PAGES[page]||page;window.location.href=url+(hash||'')}
function toast(text){const t=$('toast');if(!t)return;t.querySelector('span')&&(t.querySelector('span').textContent=text);t.classList.add('show');clearTimeout(window.__econovaToast);window.__econovaToast=setTimeout(()=>t.classList.remove('show'),2400)}
function mobileMenu(){let panel=$('workspaceMenu');if(panel)return panel;panel=document.createElement('aside');panel.id='workspaceMenu';panel.className='workspace-mobile-menu';panel.setAttribute('aria-hidden','true');panel.innerHTML=`<div class="workspace-mobile-head"><strong data-i18n="menuTitle">Workspace</strong><button type="button" data-menu-close aria-label="${tr('close')}">×</button></div><nav class="workspace-mobile-nav">${Object.entries(PAGES).map(([k,v])=>k==='overview'?'':`<a href="${v}" data-page="${k}">${tr(k)}</a>`).join('')}</nav><div class="workspace-mobile-actions"><button type="button" data-mobile-lang>${tr('language')}</button><button type="button" data-mobile-theme>${tr('theme')}</button><button type="button" data-mobile-refresh>${tr('refresh')}</button></div>`;document.body.appendChild(panel);const close=()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')};panel.querySelector('[data-menu-close]').onclick=close;panel.querySelector('[data-mobile-lang]').onclick=toggleLanguage;panel.querySelector('[data-mobile-theme]').onclick=toggleTheme;panel.querySelector('[data-mobile-refresh]').onclick=refresh;return panel}
function bindToolbar(){const menu=mobileMenu();qsa('[data-action="menu"],#mobileTools,#workspaceMenuOpen').forEach(b=>b.onclick=()=>{menu.classList.add('open');menu.setAttribute('aria-hidden','false')});qsa('[data-action="notifications"],#notificationsOpen').forEach(b=>b.onclick=()=>go('notifications'));qsa('[data-action="profile"],#profileOpen').forEach(b=>b.onclick=()=>go('profile'));qsa('[data-action="language"],#languageToggle,#langToggle').forEach(b=>b.onclick=toggleLanguage);qsa('[data-action="theme"],#themeToggle,#themeBtn').forEach(b=>b.onclick=toggleTheme);qsa('[data-action="refresh"],#refreshData').forEach(b=>b.onclick=refresh)}
function toggleLanguage(){localStorage.setItem('econova-language',lang()==='ar'?'en':'ar');applyLanguage();location.reload()}
function toggleTheme(){localStorage.setItem('econova-theme',theme()==='dark'?'light':'dark');applyTheme()}
function refresh(){toast(tr('refreshing'));window.dispatchEvent(new Event('econova:refresh'));if(typeof window.refreshEconovaQuotes==='function')window.refreshEconovaQuotes();else if(typeof window.loadMarketData==='function')window.loadMarketData();setTimeout(()=>toast(tr('updated')),900)}
function bindNavigation(){qsa('[data-page]').forEach(a=>a.onclick=()=>go(a.dataset.page));qsa('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route,b.dataset.hash||''));qsa('.workspace-nav a,.side-link,.drawer a').forEach(a=>{const h=a.getAttribute('href')||'';const m=Object.entries(PAGES).find(([,v])=>h.endsWith(v));if(m)a.onclick=e=>{e.preventDefault();go(m[0])}});qsa('[data-action="journal"]').forEach(b=>b.onclick=()=>go('performance','#journal'));qsa('[data-action="strategy"]').forEach(b=>b.onclick=()=>go('intelligence'));qsa('[data-action="risk"]').forEach(b=>b.onclick=()=>go('calendar'))}
function bindTimeframes(){qsa('[data-timeframe],.timeframe-btn,.tf-btn').forEach(b=>b.onclick=()=>{qsa('[data-timeframe],.timeframe-btn,.tf-btn').forEach(x=>x.classList.remove('active','selected'));b.classList.add('active','selected');const v=b.dataset.timeframe||b.textContent.trim();document.querySelectorAll('[data-current-timeframe]').forEach(x=>x.textContent=v);window.dispatchEvent(new CustomEvent('econova:timeframe',{detail:{timeframe:v}}))})}
function protect(){const sb=window.supabase;if(!sb?.createClient)return;const c=sb.createClient('https://feoyjasuvrqxzhskqzye.supabase.co','sb_publishable_ehho8PNFtVSRiBn7GaBl9Q_Tl1mYVT0');c.auth.getSession().then(({data})=>{if(!data?.session&&document.body.dataset.protected==='true')location.replace('../auth.html')}).catch(()=>{})}
function profile(){const save=$('saveProfile');save?.addEventListener('click',async()=>{const sb=window.supabase;if(!sb?.createClient)return toast(tr('noAction'));const c=sb.createClient('https://feoyjasuvrqxzhskqzye.supabase.co','sb_publishable_ehho8PNFtVSRiBn7GaBl9Q_Tl1mYVT0');const {data:{user}}=await c.auth.getUser();if(!user)return;const name=$('profileName')?.value?.trim();const phone=$('profilePhone')?.value?.trim();await c.auth.updateUser({data:{full_name:name,phone}});toast(tr('saved'))});const logout=$('profileLogout');logout?.addEventListener('click',async()=>{const sb=window.supabase;if(sb?.createClient){const c=sb.createClient('https://feoyjasuvrqxzhskqzye.supabase.co','sb_publishable_ehho8PNFtVSRiBn7GaBl9Q_Tl1mYVT0');await c.auth.signOut()}location.replace('../auth.html')})}
function init(){applyTheme();applyLanguage();bindToolbar();bindNavigation();bindTimeframes();profile();protect();window.addEventListener('online',()=>{const s=$('marketDataStatus');if(s)s.textContent=tr('online')});window.addEventListener('offline',()=>{const s=$('marketDataStatus');if(s)s.textContent=tr('offline')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
