(()=>{'use strict';
const $=id=>document.getElementById(id),qsa=s=>[...document.querySelectorAll(s)];
const P={overview:'index.html',markets:'markets.html',intelligence:'intelligence.html',performance:'performance.html',calendar:'risk-calendar.html',education:'education.html',notifications:'notifications.html',profile:'profile.html'};
const T={en:{dir:'ltr',language:'العربية',theme:'Theme',light:'Light',dark:'Dark',menu:'Menu',close:'Close',refresh:'Refresh',refreshing:'Refreshing market data…',updated:'Market data updated',save:'Save changes',saved:'Changes saved',logout:'Log out',online:'ONLINE · MARKET FEED AVAILABLE',offline:'OFFLINE · LAST KNOWN STATE',workspace:'Workspace',overview:'Overview',markets:'Markets',intelligence:'Intelligence',performance:'Performance',calendar:'Risk Calendar',education:'Education',notifications:'Notifications',profile:'Profile',journal:'Journal',strategy:'Strategy rules',risk:'Risk calendar'},ar:{dir:'rtl',language:'English',theme:'المظهر',light:'نهاري',dark:'ليلي',menu:'القائمة',close:'إغلاق',refresh:'تحديث',refreshing:'جارٍ تحديث بيانات السوق…',updated:'تم تحديث بيانات السوق',save:'حفظ التغييرات',saved:'تم حفظ التغييرات',logout:'تسجيل الخروج',online:'متصل · بيانات السوق متاحة',offline:'غير متصل · آخر حالة معروفة',workspace:'مساحة العمل',overview:'نظرة عامة',markets:'الأسواق',intelligence:'التحليل',performance:'الأداء',calendar:'تقويم المخاطر',education:'التعليم',notifications:'الإشعارات',profile:'الملف الشخصي',journal:'السجل',strategy:'قواعد الاستراتيجية',risk:'تقويم المخاطر'}};
const lang=()=>localStorage.getItem('econova-language')||document.documentElement.lang||'en';const tr=k=>(T[lang()]||T.en)[k]||k;const theme=()=>localStorage.getItem('econova-theme')||'dark';
function applyLanguage(){const t=T[lang()]||T.en;document.documentElement.lang=lang();document.documentElement.dir=t.dir;qsa('[data-i18n]').forEach(e=>{if(t[e.dataset.i18n])e.textContent=t[e.dataset.i18n]});qsa('[data-i18n-title]').forEach(e=>{if(t[e.dataset.i18nTitle])e.title=t[e.dataset.i18nTitle]});qsa('[data-i18n-aria]').forEach(e=>{if(t[e.dataset.i18nAria])e.setAttribute('aria-label',t[e.dataset.i18nAria])});qsa('[data-placeholder-i18n]').forEach(e=>{if(t[e.dataset.placeholderI18n])e.placeholder=t[e.dataset.placeholderI18n]});qsa('[data-lang-label]').forEach(e=>e.textContent=t.language);qsa('[data-theme-label]').forEach(e=>e.textContent=theme()==='dark'?t.light:t.dark)}
function applyTheme(){document.documentElement.dataset.theme=theme();document.body.dataset.theme=theme();qsa('[data-theme-icon]').forEach(e=>e.textContent=theme()==='dark'?'☀':'☾');applyLanguage()}
function toast(s){const t=$('toast');if(!t)return;const x=t.querySelector('span');if(x)x.textContent=s;t.classList.add('show');clearTimeout(window.__econovaToast);window.__econovaToast=setTimeout(()=>t.classList.remove('show'),2200)}
function go(k,h=''){location.href=(P[k]||k)+h}
function toggleLanguage(){localStorage.setItem('econova-language',lang()==='ar'?'en':'ar');location.reload()}
function toggleTheme(){localStorage.setItem('econova-theme',theme()==='dark'?'light':'dark');applyTheme()}
function refresh(){toast(tr('refreshing'));window.dispatchEvent(new Event('econova:refresh'));if(typeof window.refreshEconovaQuotes==='function')window.refreshEconovaQuotes();else if(typeof window.loadMarketData==='function')window.loadMarketData();setTimeout(()=>toast(tr('updated')),900)}
function menu(){let m=$('workspaceMenu');if(m)return m;m=document.createElement('aside');m.id='workspaceMenu';m.className='workspace-mobile-menu';m.setAttribute('aria-hidden','true');m.innerHTML=`<div class="workspace-mobile-head"><strong data-i18n="workspace">${tr('workspace')}</strong><button type="button" data-menu-close aria-label="${tr('close')}">×</button></div><nav class="workspace-mobile-nav">${Object.entries(P).filter(([k])=>k!=='overview').map(([k,v])=>`<a href="${v}">${tr(k)}</a>`).join('')}</nav><div class="workspace-mobile-actions"><button type="button" data-mobile-lang>${tr('language')}</button><button type="button" data-mobile-theme>${tr('theme')}</button><button type="button" data-mobile-refresh>${tr('refresh')}</button></div>`;document.body.appendChild(m);m.querySelector('[data-menu-close]').onclick=()=>m.classList.remove('open');m.querySelector('[data-mobile-lang]').onclick=toggleLanguage;m.querySelector('[data-mobile-theme]').onclick=toggleTheme;m.querySelector('[data-mobile-refresh]').onclick=refresh;return m}
function bind(){const m=menu();qsa('#mobileTools,#workspaceMenuOpen,[data-action="menu"]').forEach(b=>b.onclick=()=>m.classList.add('open'));qsa('#notificationsOpen,[data-action="notifications"]').forEach(b=>b.onclick=()=>go('notifications'));qsa('#profileOpen,[data-action="profile"]').forEach(b=>b.onclick=()=>go('profile'));qsa('#languageToggle,#langToggle,[data-action="language"]').forEach(b=>b.onclick=toggleLanguage);qsa('#themeToggle,#themeBtn,[data-action="theme"]').forEach(b=>b.onclick=toggleTheme);qsa('#refreshData,[data-action="refresh"]').forEach(b=>b.onclick=refresh);qsa('[data-action="journal"]').forEach(b=>b.onclick=()=>go('performance','#journal'));qsa('[data-action="strategy"]').forEach(b=>b.onclick=()=>go('intelligence'));qsa('[data-action="risk"]').forEach(b=>b.onclick=()=>go('calendar'));qsa('[data-timeframe],.timeframe-btn,.tf-btn').forEach(b=>b.onclick=()=>{qsa('[data-timeframe],.timeframe-btn,.tf-btn').forEach(x=>x.classList.remove('active','selected'));b.classList.add('active','selected');const v=b.dataset.timeframe||b.textContent.trim();qsa('[data-current-timeframe]').forEach(x=>x.textContent=v);window.dispatchEvent(new CustomEvent('econova:timeframe',{detail:{timeframe:v}}))})}
function protect(){const sb=window.supabase;if(!sb?.createClient)return;const c=sb.createClient('https://feoyjasuvrqxzhskqzye.supabase.co','sb_publishable_ehho8PNFtVSRiBn7GaBl9Q_Tl1mYVT0');c.auth.getSession().then(({data})=>{if(!data?.session&&document.body.dataset.protected==='true')location.replace('../auth.html')})}
function profile(){const b=$('saveProfile');if(!b||b.dataset.bound)return;b.dataset.bound='1';b.onclick=async()=>{const sb=window.supabase;if(!sb?.createClient)return;const c=sb.createClient('https://feoyjasuvrqxzhskqzye.supabase.co','sb_publishable_ehho8PNFtVSRiBn7GaBl9Q_Tl1mYVT0');const {data:{user}}=await c.auth.getUser();if(!user)return;await c.auth.updateUser({data:{full_name:$('profileName')?.value?.trim(),phone:$('profilePhone')?.value?.trim()}});toast(tr('saved'))};const l=$('profileLogout');l?.addEventListener('click',async()=>{const sb=window.supabase;if(sb?.createClient){const c=sb.createClient('https://feoyjasuvrqxzhskqzye.supabase.co','sb_publishable_ehho8PNFtVSRiBn7GaBl9Q_Tl1mYVT0');await c.auth.signOut()}location.replace('../auth.html')},{once:true})}
function init(){applyTheme();bind();profile();protect();window.addEventListener('online',()=>{const s=$('marketDataStatus');if(s)s.textContent=tr('online')});window.addEventListener('offline',()=>{const s=$('marketDataStatus');if(s)s.textContent=tr('offline')})}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
