-- HABBOUB DATABASE SCHEMA BACKUP
-- Reconstructed from the live Supabase schema on 2026-09-06.
-- This file is a recovery/backup schema. It does not contain user data or secrets.
-- Supabase project: feoyjasuvrqxzhskqzye

create extension if not exists "uuid-ossp";

-- ============================================================
-- CORE TABLES
-- ============================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  avatar_url text,
  created_at timestamptz default now()
);

create table if not exists public.admin_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin',
  created_at timestamptz default now()
);

create table if not exists public.announcements (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  content text,
  image_url text,
  link_url text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.courses (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  description text,
  thumbnail_url text,
  is_published boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.course_lessons (
  id uuid primary key default uuid_generate_v4(),
  course_id uuid references public.courses(id) on delete cascade,
  title text not null,
  description text,
  video_url text,
  lesson_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.live_sessions (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  description text,
  stream_url text,
  thumbnail_url text,
  is_live boolean default false,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.market_analysis (
  id uuid primary key default uuid_generate_v4(),
  symbol text not null,
  bias text,
  market_condition text,
  risk_level text,
  trade_status text,
  confidence numeric,
  analysis text,
  created_at timestamptz default now()
);

create table if not exists public.market_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null,
  captured_at timestamptz not null default now(),
  price numeric,
  change_1m numeric,
  change_5m numeric,
  change_15m numeric,
  change_1h numeric,
  volume numeric,
  dxy numeric,
  us10y numeric,
  vix numeric,
  metadata jsonb not null default '{}'::jsonb
);

-- ============================================================
-- NEWS / MACRO INTELLIGENCE
-- ============================================================

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  source text,
  url text,
  image_url text,
  category text default 'forex',
  impact text default 'medium',
  currency text,
  published_at timestamptz default now(),
  created_at timestamptz default now(),
  event_name text,
  actual text,
  forecast text,
  previous text,
  event_time timestamptz,
  country text,
  unit text,
  time_mode text,
  revised_previous text,
  event_status text default 'scheduled'
);

create table if not exists public.news_probability (
  id bigint generated by default as identity primary key,
  symbol text not null,
  event_name text,
  phase text default 'LIVE',
  up_probability numeric not null default 50,
  down_probability numeric not null default 50,
  confidence numeric not null default 0,
  actual_value numeric,
  forecast_value numeric,
  previous_value numeric,
  dxy_change numeric,
  us10y_change numeric,
  price_change numeric,
  historical_score numeric,
  analyst_score numeric,
  ai_score numeric,
  model_version text,
  metadata jsonb default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  news_id bigint references public.news(id) on delete cascade,
  event_time timestamptz,
  constraint news_probability_up_probability_check check (up_probability >= 0 and up_probability <= 100),
  constraint news_probability_down_probability_check check (down_probability >= 0 and down_probability <= 100),
  constraint news_probability_confidence_check check (confidence >= 0 and confidence <= 100),
  constraint news_probability_symbol_news_id_key unique (symbol, news_id)
);

create table if not exists public.historical_event_reactions (
  id bigint generated by default as identity primary key,
  event_id bigint references public.news(id) on delete cascade,
  symbol text not null,
  event_time timestamptz not null,
  price_before numeric,
  price_1m numeric,
  price_5m numeric,
  price_15m numeric,
  price_30m numeric,
  price_1h numeric,
  price_4h numeric,
  return_1m numeric,
  return_5m numeric,
  return_15m numeric,
  return_30m numeric,
  return_1h numeric,
  return_4h numeric,
  direction_5m text,
  direction_15m text,
  direction_1h text,
  dxy_return_15m numeric,
  us10y_change_15m numeric,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint historical_event_reactions_event_id_symbol_key unique (event_id, symbol)
);

-- ============================================================
-- ANALYST INTELLIGENCE
-- ============================================================

create table if not exists public.analysts (
  id bigint generated by default as identity primary key,
  name text not null,
  organization text,
  role text,
  specialty text,
  markets text[] default '{}'::text[],
  source_name text,
  source_url text,
  profile_url text,
  active boolean not null default true,
  verified boolean not null default false,
  quality_score numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_source_check_at timestamptz,
  last_source_success_at timestamptz,
  source_status text default 'pending',
  source_error text
);

create table if not exists public.analyst_predictions (
  id bigint generated by default as identity primary key,
  analyst_id bigint not null references public.analysts(id) on delete cascade,
  symbol text not null,
  event_name text,
  event_id bigint references public.news(id) on delete set null,
  prediction_time timestamptz not null default now(),
  target_time timestamptz,
  direction text,
  probability numeric,
  target_price numeric,
  horizon_minutes integer,
  forecast_text text,
  source_url text,
  source_published_at timestamptz,
  captured_at timestamptz not null default now(),
  outcome_direction text,
  outcome_return numeric,
  outcome_score numeric,
  evaluated_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  content_hash text,
  source_type text,
  captured_text text,
  constraint analyst_predictions_direction_check check (direction = any (array['bullish','bearish','neutral']::text[])),
  constraint analyst_predictions_outcome_direction_check check (outcome_direction = any (array['bullish','bearish','neutral']::text[])),
  constraint analyst_predictions_probability_check check (probability >= 0 and probability <= 100)
);

create table if not exists public.analyst_performance (
  id bigint generated by default as identity primary key,
  analyst_id bigint not null references public.analysts(id) on delete cascade,
  symbol text,
  event_category text,
  horizon_minutes integer,
  sample_size integer not null default 0,
  hit_rate numeric,
  brier_score numeric,
  mae numeric,
  avg_return_error numeric,
  streak integer not null default 0,
  weight numeric not null default 1,
  period_start timestamptz,
  period_end timestamptz,
  updated_at timestamptz not null default now(),
  constraint analyst_performance_analyst_id_symbol_event_category_horizo_key unique (analyst_id, symbol, event_category, horizon_minutes)
);

create table if not exists public.analyst_source_checks (
  id bigint generated by default as identity primary key,
  analyst_id bigint references public.analysts(id) on delete cascade,
  checked_at timestamptz not null default now(),
  success boolean not null default false,
  http_status integer,
  source_url text,
  content_hash text,
  extracted boolean not null default false,
  error text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.analyst_ingestion_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  analysts_checked integer not null default 0,
  sources_succeeded integer not null default 0,
  predictions_created integer not null default 0,
  errors integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'completed'
);

-- ============================================================
-- TRADING JOURNAL
-- ============================================================

create table if not exists public.journal_accounts (
  user_id uuid not null references auth.users(id) on delete cascade,
  journal_type text not null,
  starting_balance numeric not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, journal_type),
  constraint journal_accounts_journal_type_check check (journal_type = any (array['journal','backtest']::text[])),
  constraint journal_accounts_starting_balance_check check (starting_balance > 0)
);

create table if not exists public.trading_journal (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  journal_type text not null default 'live',
  symbol text,
  direction text,
  entry_price numeric,
  stop_loss numeric,
  take_profit numeric,
  exit_price numeric,
  risk_reward numeric,
  result text,
  notes text,
  screenshot_url text,
  created_at timestamptz default now(),
  setup text,
  r_result numeric default 0,
  account_balance numeric,
  risk_amount numeric,
  position_size numeric,
  pnl numeric,
  alignment_score numeric,
  market_score numeric,
  market_risk text,
  market_bias text,
  setup_quality numeric,
  entry_quality numeric,
  discipline_score numeric,
  constraint trading_journal_setup_quality_check check (setup_quality is null or (setup_quality >= 1 and setup_quality <= 5)),
  constraint trading_journal_entry_quality_check check (entry_quality is null or (entry_quality >= 1 and entry_quality <= 5)),
  constraint trading_journal_discipline_score_check check (discipline_score is null or (discipline_score >= 1 and discipline_score <= 5))
);

-- ============================================================
-- HELPER / SECURITY
-- ============================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_roles
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.admin_roles enable row level security;
alter table public.announcements enable row level security;
alter table public.courses enable row level security;
alter table public.course_lessons enable row level security;
alter table public.live_sessions enable row level security;
alter table public.market_analysis enable row level security;
alter table public.market_snapshots enable row level security;
alter table public.news enable row level security;
alter table public.news_probability enable row level security;
alter table public.historical_event_reactions enable row level security;
alter table public.analysts enable row level security;
alter table public.analyst_predictions enable row level security;
alter table public.analyst_performance enable row level security;
alter table public.analyst_source_checks enable row level security;
alter table public.analyst_ingestion_runs enable row level security;
alter table public.journal_accounts enable row level security;
alter table public.trading_journal enable row level security;

-- Profiles
create policy "Users can view their own profile" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "Users can create their own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "Users can delete their own profile" on public.profiles for delete to authenticated using (auth.uid() = id);

-- Admin roles
create policy "Anyone can view admin roles" on public.admin_roles for select to authenticated using (true);

-- Announcements
create policy "Anyone can view active announcements" on public.announcements for select to anon, authenticated using (is_active = true);
create policy "Admins can manage announcements" on public.announcements for all to authenticated using (is_admin()) with check (is_admin());

-- Courses
create policy "Anyone can view published courses" on public.courses for select to anon, authenticated using (is_published = true);
create policy "Admins can manage courses" on public.courses for all to authenticated using (is_admin()) with check (is_admin());

-- Course lessons
create policy "Anyone can view course lessons" on public.course_lessons for select to anon, authenticated using (exists (select 1 from public.courses where courses.id = course_lessons.course_id and courses.is_published = true));
create policy "Admins can manage course lessons" on public.course_lessons for all to authenticated using (is_admin()) with check (is_admin());

-- Live
create policy "Anyone can view live sessions" on public.live_sessions for select to anon, authenticated using (true);
create policy "Admins can manage live sessions" on public.live_sessions for all to authenticated using (is_admin()) with check (is_admin());

-- Market analysis
create policy "Anyone can view market analysis" on public.market_analysis for select to anon, authenticated using (true);
create policy "Admins can manage market analysis" on public.market_analysis for all to authenticated using (is_admin()) with check (is_admin());

-- Market snapshots
create policy "public can read market snapshots" on public.market_snapshots for select to anon, authenticated using (true);

-- News
create policy "Anyone can read news" on public.news for select to anon, authenticated using (true);

-- News probability
create policy "public read news probability" on public.news_probability for select to public using (true);

-- Historical reactions
create policy "public can read historical reactions" on public.historical_event_reactions for select to anon, authenticated using (true);

-- Analysts
create policy "public can read active analysts" on public.analysts for select to anon, authenticated using (active = true);
create policy "public can read analyst predictions" on public.analyst_predictions for select to anon, authenticated using (true);
create policy "public can read analyst performance" on public.analyst_performance for select to anon, authenticated using (true);
create policy "analyst source checks readable authenticated" on public.analyst_source_checks for select to authenticated using (true);
create policy "analyst ingestion runs readable authenticated" on public.analyst_ingestion_runs for select to authenticated using (true);

-- Journal accounts
create policy "Users can view own journal accounts" on public.journal_accounts for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create own journal accounts" on public.journal_accounts for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update own journal accounts" on public.journal_accounts for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users can delete own journal accounts" on public.journal_accounts for delete to authenticated using ((select auth.uid()) = user_id);

-- Trading journal
create policy "Users can view their own journal" on public.trading_journal for select to authenticated using (auth.uid() = user_id);
create policy "Users can insert their own journal" on public.trading_journal for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can update their own journal" on public.trading_journal for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own journal" on public.trading_journal for delete to authenticated using (auth.uid() = user_id);

-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists idx_news_event_time on public.news(event_time);
create index if not exists idx_news_published_at on public.news(published_at desc);
create index if not exists idx_news_probability_symbol on public.news_probability(symbol);
create index if not exists idx_news_probability_news_id on public.news_probability(news_id);
create index if not exists idx_news_probability_updated_at on public.news_probability(updated_at desc);
create index if not exists idx_market_analysis_symbol_created_at on public.market_analysis(symbol, created_at desc);
create index if not exists idx_market_snapshots_symbol_captured_at on public.market_snapshots(symbol, captured_at desc);
create index if not exists idx_historical_reactions_event_symbol on public.historical_event_reactions(event_id, symbol);
create index if not exists idx_analyst_predictions_symbol_time on public.analyst_predictions(symbol, prediction_time desc);
create index if not exists idx_analyst_predictions_analyst on public.analyst_predictions(analyst_id);
create index if not exists idx_analyst_source_checks_analyst on public.analyst_source_checks(analyst_id, checked_at desc);
create index if not exists idx_trading_journal_user_created on public.trading_journal(user_id, created_at desc);

-- ============================================================
-- NOTES
-- ============================================================
-- Existing live data is intentionally NOT included.
-- Cron jobs / Edge Functions are managed separately by Supabase migrations.
-- OpenRouter secrets are managed in Supabase Secrets and are intentionally NOT included.
-- Current live migration history can be inspected from Supabase migration history.
